# Generated by Django 2.2.6 on 2019-12-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(to='main_app.Guest'),
        ),
    ]
