# Generated by Django 2.2.6 on 2019-12-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20191223_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='is_attending',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_attending',
            field=models.NullBooleanField(default=None),
        ),
    ]
