# Generated by Django 3.0 on 2019-12-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20191223_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='is_attending',
            field=models.NullBooleanField(default=False),
        ),
    ]
