# Generated by Django 3.0 on 2019-12-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20191223_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='attending',
            field=models.ManyToManyField(to='main_app.Guest'),
        ),
    ]
